# Generated by Django 3.1.4 on 2021-01-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_music_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='iframe',
            field=models.CharField(default='', max_length=500),
        ),
    ]
