# Generated by Django 3.1.4 on 2021-01-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
