# Generated by Django 3.1.4 on 2021-01-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0008_auto_20210107_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='progress',
            field=models.CharField(choices=[('未付款', '未付款'), ('已付款', '已付款'), ('交易完成', '交易完成')], default='未付款', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('備貨中', '備貨中'), ('運貨中', '運貨中'), ('當天送達', '當天送達')], default='備貨中', max_length=100),
        ),
    ]
