# Generated by Django 3.1.4 on 2021-01-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0010_auto_20210107_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='time_long',
            field=models.DurationField(),
        ),
    ]
