# Generated by Django 3.1.4 on 2021-01-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0011_auto_20210108_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='time_long',
            field=models.CharField(max_length=100),
        ),
    ]
