# Generated by Django 3.1.4 on 2021-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0012_auto_20210108_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='category',
        ),
        migrations.AddField(
            model_name='singer',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
