# Generated by Django 3.1.4 on 2021-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0013_auto_20210108_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='category',
            field=models.CharField(choices=[('Male Group', 'Male Group'), ('Female Group', 'Female Group'), ('Male SOLO', 'Male SOLO'), ('Female SOLO', 'Female SOLO')], max_length=100),
        ),
    ]
